# Generated by Django 2.0.13 on 2019-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xprez', '0004_auto_20180504_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textimage',
            name='css_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
