# Generated by Django 2.1 on 2019-12-21 15:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xprez', '0006_gridboxes'),
    ]

    operations = [
        migrations.RemoveField( model_name='gridboxes', name='boxes',),
        migrations.AddField(
            model_name='gridboxes',
            name='boxes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
