# Generated by Django 2.2.24 on 2022-02-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xprez', '0010_ckeditor'),
        ('xprez', '0012_auto_20220204_1600'),
    ]

    operations = [
    ]
