# Generated by Django 4.1 on 2022-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0019_photo_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gridboxes",
            name="boxes",
            field=models.JSONField(null=True),
        ),
    ]
