# Generated by Django 4.1 on 2022-12-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0020_alter_gridboxes_boxes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ckeditor",
            options={"verbose_name": "Text Content"},
        ),
        migrations.AlterModelOptions(
            name="downloadcontent",
            options={"verbose_name": "Files"},
        ),
        migrations.AlterModelOptions(
            name="featureboxes",
            options={"verbose_name": "Feature Boxes"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery / Image"},
        ),
        migrations.AlterModelOptions(
            name="numberscontent",
            options={"verbose_name": "Numbers"},
        ),
        migrations.AlterModelOptions(
            name="quotecontent",
            options={"verbose_name": "Quote"},
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="content",
            name="page",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="xprez.contentscontainer",
            ),
        ),
    ]
