# Generated by Django 4.1.4 on 2023-12-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0021_alter_ckeditor_options_alter_downloadcontent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="alternate_color",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="background_color",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="content",
            name="padding_vertical",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "S"), (2, "M"), (3, "L"), (4, "XL")],
                default=0,
            ),
        ),
    ]
