# Generated by Django 4.1.4 on 2024-11-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xprez', '0026_alter_contentsymlink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xprez.content')),
            ],
            options={
                'abstract': False,
            },
            bases=('xprez.content',),
        ),
    ]
