# Generated by Django 4.2.17 on 2025-02-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0026_alter_contentsymlink_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                ("saved", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("changed", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "max_width_choice",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("full", "Full"),
                            ("custom", "Custom"),
                        ],
                        default="full",
                        max_length=16,
                        verbose_name="Max width",
                    ),
                ),
                (
                    "max_width_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("alternate_color", models.BooleanField(default=False)),
                ("background_color", models.CharField(blank=True, max_length=30)),
                ("css_class", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "container",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="xprez.contentscontainer",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="TextContent",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="xprez.content",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="images", null=True, blank=True)),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Target URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Text",
            },
            bases=("xprez.content",),
        ),
        migrations.AlterModelOptions(
            name="ckeditor",
            options={"verbose_name": "Text"},
        ),
        migrations.AlterField(
            model_name="content",
            name="changed",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="page",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="xprez.contentscontainer",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="content",
            name="section",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="xprez.section",
            ),
        ),
        migrations.CreateModel(
            name="SectionConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "css_breakpoint",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Basic style (&gt; 0px)"),
                            (1, "Small devices (&gt; 500px)"),
                            (2, "Tablets (&gt; 768px)"),
                            (3, "Large devices (&gt; 992px)"),
                            (4, "Desktops (&gt; 1200px)"),
                            (5, "Extra large devices (&gt; 1500px)"),
                        ],
                        default=0,
                        editable=False,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "margin_bottom_choice",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("medium", "Medium"),
                            ("small", "Small"),
                            ("custom", "Custom"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Margin bottom",
                    ),
                ),
                (
                    "margin_bottom_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "padding_left_choice",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Padding left",
                    ),
                ),
                (
                    "padding_right_choice",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Padding right",
                    ),
                ),
                (
                    "padding_top_choice",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Padding top",
                    ),
                ),
                (
                    "padding_bottom_choice",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Padding bottom",
                    ),
                ),
                (
                    "padding_left_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "padding_right_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "padding_top_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "padding_bottom_custom",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("padding_x_linked", models.BooleanField(default=True)),
                ("padding_y_linked", models.BooleanField(default=True)),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "gap_choice",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("medium", "Medium"),
                            ("small", "Small"),
                            ("custom", "Custom"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Gap",
                    ),
                ),
                ("gap_custom", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "vertical_align",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("bottom", "Bottom"),
                            ("stretch", "Stretch"),
                        ],
                        default="top",
                        max_length=20,
                    ),
                ),
                (
                    "horizontal_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                            ("stretch", "Stretch"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="xprez.section",
                        editable=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Config",
                "verbose_name_plural": "Section Configs",
                "unique_together": {("section", "css_breakpoint")},
                "ordering": ("css_breakpoint",),
            },
        ),
        migrations.CreateModel(
            name="ContentConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "css_breakpoint",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Basic style (&gt; 0px)"),
                            (1, "Small devices (&gt; 500px)"),
                            (2, "Tablets (&gt; 768px)"),
                            (3, "Large devices (&gt; 992px)"),
                            (4, "Desktops (&gt; 1200px)"),
                            (5, "Extra large devices (&gt; 1500px)"),
                        ],
                        default=0,
                        editable=False,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_configs",
                        to="xprez.content",
                        editable=False,
                    ),
                ),
                (
                    "colspan",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Column span"
                    ),
                ),
                (
                    "horizontal_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                            ("stretch", "Stretch"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                (
                    "rowspan",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Row span"
                    ),
                ),
                (
                    "vertical_align",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("bottom", "Bottom"),
                            ("stretch", "Stretch"),
                        ],
                        default="top",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Config",
                "verbose_name_plural": "Content Configs",
                "unique_together": {("content", "css_breakpoint")},
            },
        ),
        migrations.CreateModel(
            name="TextContentBaseConfig",
            fields=[
                (
                    "contentconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="xprez.contentconfig",
                    ),
                ),
                (
                    "background",
                    models.BooleanField(default=False),
                ),
                (
                    "border",
                    models.BooleanField(default=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("xprez.contentconfig",),
        ),
        migrations.CreateModel(
            name="TextContentConfig",
            fields=[
                (
                    "textcontentbaseconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="xprez.textcontentbaseconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("xprez.textcontentbaseconfig",),
        ),
    ]
