# Generated by Django 4.2.17 on 2025-02-28 10:12

from django.db import migrations

from xprez.conf import settings as xprez_settings


def forward(apps, schema_editor):
    rename_content_type(apps, schema_editor)
    migrate_to_sections(apps, schema_editor)


def _set_content_type(content):
    content.content_type = "{}.{}".format(
        content._meta.app_label,
        content._meta.object_name,
    )
    content.save()


def rename_content_type(apps, schema_editor):
    Content = apps.get_model("xprez", "Content")
    for content in Content.objects.all():
        polymorph = getattr(content, content.content_type.lower())
        _set_content_type(polymorph)


def migrate_to_sections(apps, schema_editor):
    Content = apps.get_model("xprez", "Content")
    Section = apps.get_model("xprez", "Section")

    CkEditor = apps.get_model("xprez", "CkEditor")
    MediumEditor = apps.get_model("xprez", "MediumEditor")
    TextContent = apps.get_model("xprez", "TextContent")
    GridBoxes = apps.get_model("xprez", "GridBoxes")

    ContentConfig = apps.get_model("xprez", "ContentConfig")
    TextContentConfig = apps.get_model("xprez", "TextContentConfig")

    for content in Content.objects.all():
        section = Section.objects.create(
            container=content.page,
            position=content.position,
            visible=content.visible,
            alternate_color=content.alternate_color,
            background_color=content.background_color,
            css_class=content.css_class,
            saved=True,
        )
        content.section = section
        content.position = 0
        content.saved = True
        content.save()

        # TODO: padding_top, padding_bottom
        for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
            section.configs.create(
                css_breakpoint=css_breakpoint,
                margin_bottom_choice={  # TODO
                    0: "small",
                    1: "small",
                    2: "medium",
                    3: "full",
                    4: "full",
                }[content.margin_bottom],
            )

    for medium_editor in MediumEditor.objects.all():
        content = TextContent.objects.create(
            section=medium_editor.section,
            position=medium_editor.position,
            text=medium_editor.text,
        )
        _set_content_type(content)
        medium_editor.delete()

    for ck_editor in CkEditor.objects.all():
        content = TextContent.objects.create(
            section=ck_editor.section,
            position=ck_editor.position,
            text=ck_editor.text,
        )
        _set_content_type(content)
        ck_editor.delete()

    for grid_boxes in GridBoxes.objects.all():
        for index, box in enumerate(grid_boxes.boxes or []):
            content = TextContent.objects.create(
                section=grid_boxes.section,
                position=index,
                text=box,
            )
            _set_content_type(content)
        grid_boxes.delete()

    for content in Content.objects.all():
        if content.content_type == "xprez.TextContent":
            for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
                TextContentConfig.objects.create(
                    content=content,
                    css_breakpoint=css_breakpoint,
                )
        else:
            for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
                ContentConfig.objects.create(
                    content=content,
                    css_breakpoint=css_breakpoint,
                )


def reverse(apps, schema_editor):
    raise NotImplementedError(
        """
        Reverse migration is not implemented.
        But it should be possible, feel free to implement it if needed.
    """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0027_sections_and_configs_create"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
