# Generated by Django 4.2.17 on 2025-02-28 10:12

import importlib

import django.db.models.deletion
from django.db import migrations, models

import xprez.admin.fields
from xprez.migrations._refactor_0_3_0 import (
    ContentToModule,
    migrate_containers_sections_modules,
    rename_content_types,
)


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0027_refactor_create"),
    ]

    operations = [
        migrations.RunPython(
            migrate_containers_sections_modules, migrations.RunPython.noop
        ),
        migrations.RenameModel(old_name="Gallery", new_name="GalleryModule"),
        ContentToModule(model_name="GalleryModule"),
        migrations.RenameModel(old_name="Photo", new_name="GalleryItem"),
        migrations.RenameField(
            model_name="GalleryItem", old_name="gallery", new_name="module"
        ),
        migrations.RenameField(
            model_name="GalleryItem", old_name="image", new_name="file"
        ),
        migrations.AlterField(
            model_name="GalleryItem",
            name="file",
            field=models.ImageField(upload_to="gallery"),
        ),
        migrations.AlterField(
            model_name="GalleryItem",
            name="module",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="xprez.GalleryModule",
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="saved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.RenameField(
            model_name="GalleryModule",
            old_name="crop",
            new_name="crop_old",
        ),
        migrations.AddField(
            model_name="gallerymodule",
            name="crop",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("1/1", "1:1"),
                    ("3/2", "3:2"),
                    ("4/3", "4:3"),
                    ("16/9", "16:9"),
                    ("2/3", "2:3"),
                    ("3/4", "3:4"),
                    ("9/16", "9:16"),
                ],
                default="",
                max_length=5,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="gallerymodule",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("smallest", "Extra Small"),
                    ("small", "Small"),
                    ("normal", "Normal"),
                    ("large", "Large"),
                    ("largest", "Extra Large"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Font size",
            ),
        ),
        migrations.AddField(
            model_name="gallerymodule",
            name="lightbox",
            field=models.BooleanField(default=True, verbose_name="Lightbox"),
        ),
        migrations.RenameModel(old_name="Video", new_name="VideoModule"),
        ContentToModule(model_name="VideoModule"),
        migrations.AlterField(
            model_name="videomodule",
            name="video_id",
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="videomodule",
            name="video_type",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterModelOptions(
            name="videomodule",
            options={"verbose_name": "Video"},
        ),
        migrations.RenameModel(old_name="CodeInput", new_name="CodeInputModule"),
        ContentToModule(model_name="CodeInputModule"),
        migrations.AlterModelOptions(
            name="codeinputmodule",
            options={"verbose_name": "Code Input"},
        ),
        migrations.RenameModel(old_name="NumbersContent", new_name="NumbersModule"),
        ContentToModule(model_name="NumbersModule"),
        migrations.RenameModel(old_name="Number", new_name="NumbersItem"),
        migrations.RenameField(
            model_name="NumbersItem", old_name="content", new_name="module"
        ),
        migrations.RenameField(
            model_name="NumbersItem", old_name="title", new_name="caption"
        ),
        migrations.AlterField(
            model_name="numbersitem",
            name="module",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="xprez.numbersmodule",
            ),
        ),
        migrations.AlterModelOptions(
            name="NumbersItem",
            options={"ordering": ("position",)},
        ),
        migrations.AddField(
            model_name="numbersitem",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="numbersitem",
            name="saved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="numbersmodule",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("smallest", "Extra Small"),
                    ("small", "Small"),
                    ("normal", "Normal"),
                    ("large", "Large"),
                    ("largest", "Extra Large"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Font size",
            ),
        ),
        migrations.RenameModel(old_name="CodeTemplate", new_name="CodeTemplateModule"),
        ContentToModule(model_name="CodeTemplateModule"),
        migrations.AlterModelOptions(
            name="codetemplatemodule",
            options={"verbose_name": "Code Template"},
        ),
        migrations.AlterField(
            model_name="codetemplatemodule",
            name="template_name",
            field=xprez.admin.fields.TemplatePathField(
                blank=True, match="^(?!\\.).+", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="codetemplatemodule",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("smallest", "Extra Small"),
                    ("small", "Small"),
                    ("normal", "Normal"),
                    ("large", "Large"),
                    ("largest", "Extra Large"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Font size",
            ),
        ),
        migrations.RenameModel(old_name="DownloadContent", new_name="FilesModule"),
        ContentToModule(model_name="FilesModule"),
        migrations.RenameModel(old_name="Attachment", new_name="FilesItem"),
        migrations.RenameField(
            model_name="FilesItem", old_name="content", new_name="module"
        ),
        migrations.AlterField(
            model_name="FilesItem",
            name="module",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="xprez.FilesModule",
            ),
        ),
        migrations.RenameField(
            model_name="FilesItem",
            old_name="name",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="FilesItem",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="filesitem",
            name="saved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="filesitem",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="filesmodule",
            name="font_size",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("smallest", "Extra Small"),
                    ("small", "Small"),
                    ("normal", "Normal"),
                    ("large", "Large"),
                    ("largest", "Extra Large"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Font size",
            ),
        ),
        migrations.RenameModel(old_name="ContentSymlink", new_name="ModuleSymlink"),
        ContentToModule(model_name="ModuleSymlink"),
        migrations.AlterField(
            model_name="modulesymlink",
            name="symlink",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="symlinked_module_set",
                to="xprez.Module",
            ),
        ),
        migrations.RunPython(rename_content_types, migrations.RunPython.noop),
    ]
