# Generated by Django 4.2.17 on 2025-02-28 10:12

from django.db import migrations


def _content_type(obj):
    return "{}.{}".format(
        obj._meta.app_label,
        obj._meta.object_name,
    )


def _set_module(module, section, position, **kwargs):
    module.content_type = _content_type(module)
    module.section = section
    module.position = position
    module.saved = True
    module.save()
    return module


def forward(apps, schema_editor):
    # legacy models
    ContentsContainer = apps.get_model("xprez", "ContentsContainer")
    Content = apps.get_model("xprez", "Content")

    # new models
    Container = apps.get_model("xprez", "Container")
    Module = apps.get_model("xprez", "Module")
    Section = apps.get_model("xprez", "Section")
    ModuleConfig = apps.get_model("xprez", "ModuleConfig")

    TextModule = apps.get_model("xprez", "TextModule")
    TextModuleConfig = apps.get_model("xprez", "TextModuleConfig")

    print("")
    print("Count: ", Module.objects.all().count())
    for old_container in ContentsContainer.objects.all():
        old_container_polymorph = getattr(
            old_container, old_container.content_type.lower()
        )
        container = Container.objects.create(
            id=old_container.id,
            content_type=_content_type(old_container_polymorph),
        )
        for old_content_base in Content.objects.filter(page=old_container):
            print(old_content_base.content_type)
            old_content = getattr(
                old_content_base, old_content_base.content_type.lower()
            )
            section = Section.objects.create(
                container=container,
                position=old_content.position,
                visible=old_content.visible,
                alternate_color=old_content.alternate_color,
                background_color=old_content.background_color,
                css_class=old_content.css_class,
                saved=True,
            )

            if old_content.content_type in ["ckeditor", "mediumeditor"]:
                module = _set_module(TextModule(text=old_content.text), section, 0)
            elif old_content.content_type == "gridboxes":
                for index, box in enumerate(old_content.boxes):
                    module = _set_module(TextModule(text=box), section, index)
            else:  #
                module = getattr(
                    old_content_base, old_content_base.content_type.lower()
                )
                module.content_type = _content_type(module)
                module.section = section
                module.position = 0
                module.saved = True
                module.save()
            print(module.content_type)


# def copy_contents_container_to_container(apps, schema_editor):
#     """
#     Copy base table rows from ContentsContainer -> Container while preserving PKs.
#     """
#     ContentsContainer = apps.get_model("xprez", "ContentsContainer")
#     Container = apps.get_model("xprez", "Container")

#     for old in ContentsContainer.objects.all():
#         container = Container.objects.create(
#             id=old.id,
#             content_type=old.content_type,
#         )


# def copy_content_to_module(apps, schema_editor):
#     """
#     Copy base table rows from Content -> Module while preserving PKs.

#     Module requires a non-null Section FK. At this point we don't yet know the
#     final section mapping, so we attach all copied Modules to a single
#     placeholder Section and let later migrations reorganize them.
#     """
#     Content = apps.get_model("xprez", "Content")
#     Module = apps.get_model("xprez", "Module")
#     Section = apps.get_model("xprez", "Section")

#     placeholder_section, _ = Section.objects.get_or_create(
#         container=None,
#         position=0,
#         css_class="__xprez_migration_placeholder__",
#         defaults={"saved": False},
#     )

#     existing_ids = set(Module.objects.values_list("id", flat=True))
#     to_create = []
#     for old in Content.objects.all():
#         if old.id in existing_ids:
#             continue
#         to_create.append(
#             Module(
#                 id=old.id,
#                 section=placeholder_section,
#                 saved=False,
#                 position=old.position,
#                 content_type=old.content_type,
#                 css_class=getattr(old, "css_class", None),
#                 created=old.created,
#                 changed=old.changed,
#             )
#         )

#     if to_create:
#         Module.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0027_refactor_create"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
        # migrations.RunPython(copy_content_to_module),
        # migrations.RunPython(copy_contents_container_to_container),
        # migrations.RenameModel(old_name="ContentsContainer", new_name="Container"),
        # migrations.AlterField(
        #     model_name="module",
        #     name="changed",
        #     field=models.DateTimeField(auto_now=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="created",
        #     field=models.DateTimeField(auto_now_add=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="page",
        #     field=models.ForeignKey(
        #         editable=False,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="modules",
        #         to="xprez.container",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="position",
        #     field=models.PositiveSmallIntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name="module",
        #     name="section",
        #     field=models.ForeignKey(
        #         editable=False,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="modules",
        #         to="xprez.section",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="module",
        #     name="saved",
        #     field=models.BooleanField(default=False, editable=False),
        # ),
    ]
