# Generated by Django 4.2.17 on 2025-02-28 10:12

from django.core.management.color import no_style
from django.db import migrations
from django.utils import timezone


def _content_type(obj):
    return "{}.{}".format(
        obj._meta.app_label,
        obj._meta.object_name,
    )


def _reset_sequences(schema_editor, models):
    """
    When we insert rows with explicit PKs (e.g. id=old_id), Postgres sequences
    may remain behind; later inserts that rely on the sequence can then collide.
    """
    for sql in schema_editor.connection.ops.sequence_reset_sql(no_style(), models):
        schema_editor.execute(sql)


def _module_base_attributes(module_base):
    attrs = {}
    for attr in ["section", "position", "saved", "created", "changed"]:
        attrs[attr] = getattr(module_base, attr)
    return attrs


def _set_module(module, section, position, **kwargs):
    module.content_type = _content_type(module)
    module.section = section
    module.position = position
    module.saved = True
    module.save()
    return module


def forward(apps, schema_editor):
    print("")
    # legacy models
    ContentsContainer = apps.get_model("xprez", "ContentsContainer")
    Content = apps.get_model("xprez", "Content")

    # new models
    Container = apps.get_model("xprez", "Container")
    Module = apps.get_model("xprez", "Module")
    Section = apps.get_model("xprez", "Section")
    ModuleConfig = apps.get_model("xprez", "ModuleConfig")

    TextModule = apps.get_model("xprez", "TextModule")
    TextModuleConfig = apps.get_model("xprez", "TextModuleConfig")

    # copy to containers, sections and modules
    for old_container in ContentsContainer.objects.all():
        old_container_polymorph = getattr(
            old_container, old_container.content_type.lower()
        )
        container = Container.objects.create(
            id=old_container.id,
            content_type=_content_type(old_container_polymorph),
        )
        for old_content_base in Content.objects.filter(page=old_container):
            old_content = getattr(
                old_content_base, old_content_base.content_type.lower()
            )
            section = Section.objects.create(
                container=container,
                position=old_content.position,
                visible=old_content.visible,
                alternate_color=old_content.alternate_color,
                background_color=old_content.background_color,
                css_class=old_content.css_class,
                saved=True,
            )

            module_base = Module.objects.create(
                id=old_content_base.id,
                content_type=_content_type(old_content),
                section=section,
                position=0,
                saved=True,
                created=timezone.now(),
                changed=timezone.now(),
            )

    _reset_sequences(schema_editor, [Container, Module])

    for module_base in Module.objects.all():
        old_content_base = Content.objects.get(id=module_base.id)
        old_content = getattr(old_content_base, old_content_base.content_type.lower())
        if old_content.content_type in ["ckeditor", "mediumeditor"]:
            new_module = TextModule(
                text=old_content.text,
                **_module_base_attributes(module_base),
            )
            new_module.content_type = _content_type(new_module)
            new_module.save()
            module_base.delete()
        elif old_content.content_type == "gridboxes":
            for index, box in enumerate(old_content.boxes):
                attributes = _module_base_attributes(module_base)
                attributes["position"] = index
                new_module = TextModule(
                    text=box,
                    **attributes,
                )
                new_module.content_type = _content_type(new_module)
                new_module.save()
            module_base.delete()
        elif old_content.content_type == "textimage":
            # TODO: convert textimage to text+gallery
            module_base.delete()
            continue
    print("---")
    for module in Module.objects.all():
        print(module.content_type)

    # for old_content_base in Content.objects.all():
    #     old_content = getattr(old_content_base, old_content_base.content_type.lower())
    #     print(old_content.content_type)
    #     module_base = Module.objects.get(id=old_content.id)
    #     if old_content.content_type in ["ckeditor", "mediumeditor"]:
    #         module = TextModule.objects.create(
    #             text=old_content.text,
    #             **_module_base_attributes(module_base),
    #         )
    #         module_base.delete()
    #     elif old_content.content_type == "gridboxes":
    #         for index, box in enumerate(old_content.boxes):
    #             module = TextModule(
    #                 section=module_base.section, position=index, text=box
    #             )
    #             module.content_type = _content_type(module)
    #             module.save()
    #         module_base.delete()
    #     elif old_content.content_type == "textimage":
    #         # TODO: convert textimage to text+gallery
    #         continue

    # if old_content.content_type in ["ckeditor", "mediumeditor"]:
    #     module = _set_module(TextModule(text=old_content.text), section, 0)
    # elif old_content.content_type == "gridboxes":
    #     for index, box in enumerate(old_content.boxes):
    #         module = _set_module(TextModule(text=box), section, index)
    # else:  #
    #     Module.objects.create(
    #         content_type=old_content_base.content_type,
    #         section=section,
    #         position=0,
    #         saved=True,
    #     )
    #     # module = getattr(
    #     #     old_content_base, old_content_base.content_type.lower()
    #     # )
    #     # module.content_type = _content_type(module)
    #     # module.section = section
    #     # module.position = 0
    #     # module.saved = True
    #     # module.save()
    # print(module.content_type)


# def copy_contents_container_to_container(apps, schema_editor):
#     """
#     Copy base table rows from ContentsContainer -> Container while preserving PKs.
#     """
#     ContentsContainer = apps.get_model("xprez", "ContentsContainer")
#     Container = apps.get_model("xprez", "Container")

#     for old in ContentsContainer.objects.all():
#         container = Container.objects.create(
#             id=old.id,
#             content_type=old.content_type,
#         )


# def copy_content_to_module(apps, schema_editor):
#     """
#     Copy base table rows from Content -> Module while preserving PKs.

#     Module requires a non-null Section FK. At this point we don't yet know the
#     final section mapping, so we attach all copied Modules to a single
#     placeholder Section and let later migrations reorganize them.
#     """
#     Content = apps.get_model("xprez", "Content")
#     Module = apps.get_model("xprez", "Module")
#     Section = apps.get_model("xprez", "Section")

#     placeholder_section, _ = Section.objects.get_or_create(
#         container=None,
#         position=0,
#         css_class="__xprez_migration_placeholder__",
#         defaults={"saved": False},
#     )

#     existing_ids = set(Module.objects.values_list("id", flat=True))
#     to_create = []
#     for old in Content.objects.all():
#         if old.id in existing_ids:
#             continue
#         to_create.append(
#             Module(
#                 id=old.id,
#                 section=placeholder_section,
#                 saved=False,
#                 position=old.position,
#                 content_type=old.content_type,
#                 css_class=getattr(old, "css_class", None),
#                 created=old.created,
#                 changed=old.changed,
#             )
#         )

#     if to_create:
#         Module.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0027_refactor_create"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
        # migrations.RunPython(copy_content_to_module),
        # migrations.RunPython(copy_contents_container_to_container),
        # migrations.RenameModel(old_name="ContentsContainer", new_name="Container"),
        # migrations.AlterField(
        #     model_name="module",
        #     name="changed",
        #     field=models.DateTimeField(auto_now=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="created",
        #     field=models.DateTimeField(auto_now_add=True, db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="page",
        #     field=models.ForeignKey(
        #         editable=False,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="modules",
        #         to="xprez.container",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="module",
        #     name="position",
        #     field=models.PositiveSmallIntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name="module",
        #     name="section",
        #     field=models.ForeignKey(
        #         editable=False,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="modules",
        #         to="xprez.section",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="module",
        #     name="saved",
        #     field=models.BooleanField(default=False, editable=False),
        # ),
    ]
