# Generated by Django 4.2.17 on 2025-02-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0028_migrate_to_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="alternate_color",
        ),
        migrations.RemoveField(
            model_name="content",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="content",
            name="css_class",
        ),
        migrations.RemoveField(
            model_name="content",
            name="margin_bottom",
        ),
        migrations.RemoveField(
            model_name="content",
            name="padding_bottom",
        ),
        migrations.RemoveField(
            model_name="content",
            name="padding_top",
        ),
        migrations.RemoveField(
            model_name="content",
            name="page",
        ),
        migrations.RemoveField(
            model_name="content",
            name="visible",
        ),
        migrations.AlterField(
            model_name="content",
            name="section",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="xprez.section",
            ),
        ),
    ]
