# Generated by Django 4.2.17 on 2025-02-28 10:12

import django.db.models.deletion
from django.db import migrations, models

from xprez.conf import settings as xprez_settings
from xprez.migrations._operations import ContentToModule


def forward(apps, schema_editor):
    ContentsContainer = apps.get_model("xprez", "ContentsContainer")
    for old_container in ContentsContainer.objects.all():
        container = Container.objects.create(
            id=old_container.id,
            content_type=old_container.content_type,
        )

    # migrate_to_sections(apps, schema_editor)
    # rename_content_type(apps, schema_editor)


def _set_content_type(obj):
    obj.content_type = "{}.{}".format(
        obj._meta.app_label,
        obj._meta.object_name,
    )
    obj.save()


def rename_content_type(apps, schema_editor):
    Module = apps.get_model("xprez", "Module")
    for module in Module.objects.all():
        polymorph = getattr(module, module.content_type.lower())
        _set_content_type(polymorph)

    Container = apps.get_model("xprez", "Container")
    for container in Container.objects.all():
        polymorph = getattr(container, container.content_type.lower())
        _set_content_type(polymorph)


def migrate_to_sections(apps, schema_editor):
    Content = apps.get_model("xprez", "Content")

    Module = apps.get_model("xprez", "Module")
    Section = apps.get_model("xprez", "Section")

    TextModule = apps.get_model("xprez", "TextModule")
    CkEditor = apps.get_model("xprez", "CkEditor")
    MediumEditor = apps.get_model("xprez", "MediumEditor")
    GridBoxes = apps.get_model("xprez", "GridBoxes")
    TextImage = apps.get_model("xprez", "TextImage")

    ModuleConfig = apps.get_model("xprez", "ModuleConfig")
    TextModuleConfig = apps.get_model("xprez", "TextModuleConfig")

    # for module in Module.objects.all():
    #     content = Content.objects.get(id=module.id)

    #     section = Section.objects.create(
    #         container_id=content.page_id,
    #         position=content.position,
    #         visible=content.visible,
    #         alternate_color=content.alternate_color,
    #         background_color=content.background_color,
    #         css_class=content.css_class,
    #         saved=True,
    #     )
    #     module.section = section
    #     module.position = 0
    #     module.saved = True
    #     module.save()

    #     # TODO: padding_top, padding_bottom
    #     for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
    #         section.configs.create(
    #             css_breakpoint=css_breakpoint,
    #             margin_bottom_choice={  # TODO
    #                 0: "small",
    #                 1: "small",
    #                 2: "medium",
    #                 3: "full",
    #                 4: "full",
    #             }[content.margin_bottom],
    #         )

    # for medium_editor in MediumEditor.objects.all():
    #     content = Content.objects.get(id=medium_editor.id)
    #     module = TextModule.objects.create(
    #         section_id=content.section_id,
    #         section=medium_editor.section,
    #         position=medium_editor.position,
    #         text=medium_editor.text,
    #         saved=True,
    #     )
    #     _set_content_type(module)
    #     medium_editor.delete()

    # for ck_editor in CkEditor.objects.all():
    #     module = TextModule.objects.create(
    #         section=ck_editor.section,
    #         position=ck_editor.position,
    #         text=ck_editor.text,
    #         saved=True,
    #     )
    #     _set_content_type(module)
    #     ck_editor.delete()

    # for grid_boxes in GridBoxes.objects.all():
    #     for index, box in enumerate(grid_boxes.boxes or []):
    #         module = TextModule.objects.create(
    #             section=grid_boxes.section,
    #             position=index,
    #             text=box,
    #             saved=True,
    #         )
    #         _set_content_type(module)
    #     grid_boxes.delete()

    # for text_image in TextImage.objects.all():
    #     raise NotImplementedError("TODO: TextImage migration is not implemented yet")

    for module in Module.objects.all():
        if module.content_type == "xprez.TextModule":
            for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
                TextModuleConfig.objects.create(
                    module=module,
                    css_breakpoint=css_breakpoint,
                )
        else:
            for css_breakpoint in xprez_settings.XPREZ_BREAKPOINTS.keys():
                ModuleConfig.objects.create(
                    module=module,
                    css_breakpoint=css_breakpoint,
                )


def reverse(apps, schema_editor):
    raise NotImplementedError(
        """
        Reverse migration is not implemented.
        But it should be possible, feel free to implement it if needed.
    """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0028_refactor_migrate"),
    ]

    operations = [
        migrations.DeleteModel("Content"),
        migrations.DeleteModel("ContentsContainer"),
        migrations.DeleteModel("CkEditor"),
        migrations.DeleteModel("MediumEditor"),
        migrations.DeleteModel("GridBoxes"),
        migrations.DeleteModel("FeatureBoxes"),
        migrations.DeleteModel("TextImage"),
    ]
