# Generated by Django 4.2.17 on 2025-02-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0028_sections_and_configs_migrate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="alternate_color",
        ),
        migrations.RemoveField(
            model_name="content",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="content",
            name="margin_bottom",
        ),
        migrations.RemoveField(
            model_name="content",
            name="padding_bottom",
        ),
        migrations.RemoveField(
            model_name="content",
            name="padding_top",
        ),
        migrations.RemoveField(
            model_name="content",
            name="page",
        ),
        migrations.RemoveField(
            model_name="content",
            name="visible",
        ),
        migrations.AlterField(
            model_name="content",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="xprez.section",
            ),
        ),
    ]
