# Generated by Django 4.2.17 on 2025-02-28 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0028_refactor_migrate"),
    ]

    operations = [
        migrations.DeleteModel("Content"),
        migrations.DeleteModel("ContentsContainer"),
        migrations.DeleteModel("CkEditor"),
        migrations.DeleteModel("MediumEditor"),
        migrations.DeleteModel("GridBoxes"),
        migrations.DeleteModel("FeatureBoxes"),
        migrations.DeleteModel("TextImage"),
        migrations.DeleteModel(name="Quote"),
        migrations.DeleteModel(name="QuoteContent"),
        migrations.RemoveField(model_name="GalleryModule", name="crop_old"),
        migrations.RemoveField(model_name="GalleryModule", name="divided"),
        migrations.RemoveField(model_name="GalleryModule", name="columns"),
        migrations.RemoveField(model_name="GalleryModule", name="width"),
        migrations.RemoveField(model_name="VideoModule", name="width"),
    ]
