# Generated by Django 4.2.29 on 2026-05-06 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xprez", "0030_refactor_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccordionModule",
            fields=[
                (
                    "module_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="xprez.module",
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("unset", "Unset"),
                            ("smallest", "Extra Small"),
                            ("small", "Small"),
                            ("normal", "Normal"),
                            ("large", "Large"),
                            ("largest", "Extra Large"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Font size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accordion",
            },
            bases=("xprez.module",),
        ),
        migrations.CreateModel(
            name="AccordionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved", models.BooleanField(default=False, editable=False)),
                ("position", models.PositiveSmallIntegerField(blank=True, default=0)),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                ("text", models.TextField(blank=True, verbose_name="Text")),
                (
                    "module",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="xprez.accordionmodule",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "abstract": False,
            },
        ),
    ]
