# Generated by Django 4.2.26 on 2026-05-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0031_accordionmodule_accordionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleconfig",
            name="horizontal_align_flex",
            field=models.CharField(
                choices=[
                    ("flex-start", "Flex Start"),
                    ("center", "Center"),
                    ("flex-end", "Flex End"),
                ],
                default="flex-start",
                max_length=20,
                verbose_name="Horizontal align (flex)",
            ),
        ),
        migrations.AlterField(
            model_name="sectionconfig",
            name="horizontal_align_grid",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("center", "Center"),
                    ("end", "End"),
                    ("stretch", "Stretch"),
                ],
                default="start",
                max_length=20,
            ),
        ),
    ]
