# Generated by Django 4.2.26 on 2026-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0032_alter_moduleconfig_horizontal_align_flex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleconfig",
            name="max_width",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Max width"
            ),
        ),
    ]
