# Generated by Django 4.1.4 on 2026-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0033_moduleconfig_max_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryconfig",
            name="items_border_radius_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("custom", "Custom"),
                ],
                default="",
                max_length=20,
                verbose_name="Items border radius",
            ),
        ),
        migrations.AddField(
            model_name="galleryconfig",
            name="items_border_radius_custom",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moduleconfig",
            name="horizontal_align_flex",
            field=models.CharField(
                choices=[
                    ("flex-start", "Start"),
                    ("center", "Center"),
                    ("flex-end", "End"),
                ],
                default="flex-start",
                max_length=20,
                verbose_name="Horizontal align (flex)",
            ),
        ),
        migrations.AlterField(
            model_name="moduleconfig",
            name="vertical_align_flex",
            field=models.CharField(
                choices=[
                    ("flex-start", "Start"),
                    ("center", "Center"),
                    ("flex-end", "End"),
                    ("stretch", "Stretch"),
                ],
                default="flex-start",
                max_length=20,
                verbose_name="Vertical align (flex)",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="max_width_choice",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("full", "Full"),
                    ("custom", "Custom"),
                ],
                default="medium",
                max_length=16,
                verbose_name="Max width",
            ),
        ),
    ]
