# Generated by Django 4.2 on 2026-06-04 18:27

from django.db import migrations
import xprez.admin.fields


class Migration(migrations.Migration):

    dependencies = [
        ("xprez", "0034_galleryconfig_items_border_radius_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleconfig",
            name="aspect_ratio",
            field=xprez.admin.fields.AspectRatioField(
                blank=True, default="", max_length=20
            ),
        ),
    ]
